In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [2]:
# save filepath to variable for easier access
mentalhealth_file_path = '/home/steph/PCUBED/mental-health-research-proj/student_mental_health.csv'
# read the data and store it in DataFrame (mentalhealth_data)
mentalhealth_data = pd.read_csv(mentalhealth_file_path)

In [3]:
# displays questionnaire questions
mentalhealth_data.columns

Index(['Timestamp', 'Choose_your_gender', 'Age', 'What_is_your_course',
       'Your_current_year_of_Study', 'What_is_your_CGPA', 'Marital_status',
       'Do_you_have_Depression', 'Do_you_have_Anxiety',
       'Do_you_have_Panic_attack',
       'Did_you_seek_any_specialist_for_a_treatment'],
      dtype='object')

In [4]:
# dropna drops missing values 
mentalhealth_data = mentalhealth_data.dropna(axis=0)

In [5]:
# gives a rundown of the data in the dataset
mentalhealth_data.describe(include = 'all')

,Timestamp,Choose_your_gender,Age,What_is_your_course,Your_current_year_of_Study,What_is_your_CGPA,Marital_status,Do_you_have_Depression,Do_you_have_Anxiety,Do_you_have_Panic_attack,Did_you_seek_any_specialist_for_a_treatment
count,100,100,100.00000,100,100,100,100,100,100,100,100
unique,91,2,NaN,49,7,6,2,2,2,2,2
top,8/7/2020 12:39,Female,NaN,BCS,year 1,3.50 - 4.00,No,No,No,No,No
freq,3,75,NaN,18,40,47,84,65,66,67,94
mean,NaN,NaN,20.53000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,2.49628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,18.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,18.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,19.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,23.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,24.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# prediction targets (what we are trying to predict with the data provided)
a = mentalhealth_data.Do_you_have_Depression
b = mentalhealth_data.Do_you_have_Anxiety
c = mentalhealth_data.Do_you_have_Panic_attack
d = mentalhealth_data.Did_you_seek_any_specialist_for_a_treatment

In [7]:
# columns to be used to make predictions that may affect the outcome
mentalhealth_features = ['Choose_your_gender', 'Age', 'What_is_your_course', 'Your_current_year_of_Study', 'What_is_your_CGPA', 'Marital_status']
X = mentalhealth_data[mentalhealth_features]
X.describe(include = 'all')

,Choose_your_gender,Age,What_is_your_course,Your_current_year_of_Study,What_is_your_CGPA,Marital_status
count,100,100.00000,100,100,100,100
unique,2,NaN,49,7,6,2
top,Female,NaN,BCS,year 1,3.50 - 4.00,No
freq,75,NaN,18,40,47,84
mean,NaN,20.53000,NaN,NaN,NaN,NaN
std,NaN,2.49628,NaN,NaN,NaN,NaN
min,NaN,18.00000,NaN,NaN,NaN,NaN
25%,NaN,18.00000,NaN,NaN,NaN,NaN
50%,NaN,19.00000,NaN,NaN,NaN,NaN
75%,NaN,23.00000,NaN,NaN,NaN,NaN
max,NaN,24.00000,NaN,NaN,NaN,NaN

In [13]:
# defines the model - specify num for random state to ensure same results each run
mentalhealth_model = DecisionTreeRegressor(random_state = 1)
# Fit model
mentalhealth_model.fit(X,a)
DecisionTreeRegressor(random_state = 1)

ValueError: could not convert string to float: 'Female'